name: "CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
          #submodules: recursive

      - name: Install system dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y darcs

      - name: Setup OCaml and OPAM
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.14.1"
          opam-version: "2.1"

      - name: Retrieve the opam cache
        id: cache-ocaml
        uses: actions/cache@v3
        with:
          path: ~/.opam
          key: ${{ runner.os }}-opam-${{ hashFiles('**/opam.locked') }}
          restore-keys: |
            ${{ runner.os }}-opam-
        continue-on-error: true

      - name: Install Coq and dependencies
        run: |
          opam update
          opam switch create . 4.14.1 --no-install --reuse
          eval "$(opam env)"
          opam install coq.8.18.0 coq-mathcomp-analysis.X.Y.Z dune

      - name: Build Coq project
        run: make coq

      - name: Run Extraction
        run: make extract