name: "CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        #submodules: recursive

      - name: Install system dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y darcs

      - name: Setup OCaml and OPAM
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.14.1"
          opam-version: "2.1"

      - name: Retrieve the opam cache
        id: cache-ocaml
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.opam
          key: ${{ runner.os }}-opam-${{ hashFiles('**/opam.locked') }}
          restore-keys: |
            ${{ runner.os }}-opam-

      - name: Debug Search for coq-mathcomp
        run: |
          opam update
          opam search coq-mathcomp
        continue-on-error: true

      - name: Add Coq opam repository
        run: opam repo add coq-released https://coq.inria.fr/opam/released

      - name: Install Coq and dependencies
        run: |
          opam update
          eval "$(opam env)"
          opam install coq.8.18.0 coq-mathcomp-analysis dune
      - name: Install dune
        run: opam install dune y

      - name: Build Coq project
        run: dune build

      - name: Run Extraction
        run: make extract
